prettier

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,79 +1,79 @@
 name: Build
 
 on:
-  push:
-  pull_request:
-    branches: [ main ]
-  workflow_dispatch:
+    push:
+    pull_request:
+        branches: [main]
+    workflow_dispatch:
 
 permissions:
-  contents: write
+    contents: write
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v5
+    build:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout
+              uses: actions/checkout@v5
 
-      - name: Use Node.js 24
-        uses: actions/setup-node@v4
-        with:
-          node-version: 24
-          cache: 'npm'
+            - name: Use Node.js 24
+              uses: actions/setup-node@v4
+              with:
+                  node-version: 24
+                  cache: 'npm'
 
-      - name: Install dependencies
-        run: npm ci
+            - name: Install dependencies
+              run: npm ci
 
-      - name: Run linter
-        run: npm run lint
+            - name: Run linter
+              run: npm run lint
 
-      - name: Build
-        run: npm run build --silent
+            - name: Build
+              run: npm run build --silent
 
-      - name: Verify build directory
-        run: test -d dist && echo "dist directory exists." || (echo "dist directory missing" && exit 1)
+            - name: Verify build directory
+              run: test -d dist && echo "dist directory exists." || (echo "dist directory missing" && exit 1)
 
-  release:
-    runs-on: ubuntu-latest
-    needs: build
-    if: github.ref == 'refs/heads/main'
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v5
-        with:
-          fetch-depth: 0
-          fetch-tags: true
+    release:
+        runs-on: ubuntu-latest
+        needs: build
+        if: github.ref == 'refs/heads/main'
+        steps:
+            - name: Checkout
+              uses: actions/checkout@v5
+              with:
+                  fetch-depth: 0
+                  fetch-tags: true
 
-      - name: Create a tag
-        run: |
-          VERSION=$(git describe --tags --abbrev=0)
+            - name: Create a tag
+              run: |
+                  VERSION=$(git describe --tags --abbrev=0)
 
-          MAJOR_VERSION=$(echo $VERSION | cut -d. -f 1)
-          MINOR_VERSION=$(echo $VERSION | cut -d. -f 2)
+                  MAJOR_VERSION=$(echo $VERSION | cut -d. -f 1)
+                  MINOR_VERSION=$(echo $VERSION | cut -d. -f 2)
 
-          NEW_MINOR_VERSION=$((MINOR_VERSION + 1))
+                  NEW_MINOR_VERSION=$((MINOR_VERSION + 1))
 
-          NEW_VERSION="${MAJOR_VERSION}.${NEW_MINOR_VERSION}"
-          git tag ${NEW_VERSION}
-          git push --tags
-          echo "JAPANESE_FLASHCARDS_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
-        
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
+                  NEW_VERSION="${MAJOR_VERSION}.${NEW_MINOR_VERSION}"
+                  git tag ${NEW_VERSION}
+                  git push --tags
+                  echo "JAPANESE_FLASHCARDS_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+            - name: Set up QEMU
+              uses: docker/setup-qemu-action@v3
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+            - name: Set up Docker Buildx
+              uses: docker/setup-buildx-action@v3
 
-      - name: Build and push
-        uses: docker/build-push-action@v6
-        with:
-          platforms: linux/amd64,linux/arm64
-          push: true
-          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jflashcards:${{ env.JAPANESE_FLASHCARDS_VERSION }}
+            - name: Login to Docker Hub
+              uses: docker/login-action@v3
+              with:
+                  username: ${{ secrets.DOCKERHUB_USERNAME }}
+                  password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+            - name: Build and push
+              uses: docker/build-push-action@v6
+              with:
+                  platforms: linux/amd64,linux/arm64
+                  push: true
+                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/jflashcards:${{ env.JAPANESE_FLASHCARDS_VERSION }}
